# Pull request labeler configuration
# See https://github.com/actions/labeler

'component:provider':
  - changed-files:
    - any-glob-to-any-file: 'src/asmf/providers/**/*'

'component:parser':
  - changed-files:
    - any-glob-to-any-file: 'src/asmf/parsers/**/*'

'component:analyzer':
  - changed-files:
    - any-glob-to-any-file: 'src/asmf/analyzers/**/*'

'component:utils':
  - changed-files:
    - any-glob-to-any-file: 'src/asmf/utils/**/*'

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

'testing':
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*', '**/*test*.py']

'ci':
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*', '.github/**/*.yml', 'Dockerfile']

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['pyproject.toml', 'requirements*.txt']
